# This is a basic workflow to help you get started with Actions

name: GitHub Action next2 flow to Docker hub 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build-push-images:
    name: Budowa i publikacja obrazow na repozytorium
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
	
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          file: ./Dockerfile
          push: true
          tags: |
            gabbla1/tch:zad1qemu
            ghcr.io/gabbl0/docker-zad1/zad1qemu:latest
          cache-from: type=registry,ref=gabbla1/tch:zad1qemu
          cache-to: type=inline
          
